#!/bin/bash

# Copyright 2015 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and 
# limitations under the License.

# Kubernetes branch to get the OpenAPI spec from.
export KUBERNETES_BRANCH="release-1.16"

# client version for packaging and releasing. It can
# be different than SPEC_VERSION.
export CLIENT_VERSION="0.1"

# Name of the release package
export PACKAGE_NAME="kubernetes"

export USERNAME="kubernetes"

OPENAPI_GENERATOR_COMMIT=44f5f2bdd8ef56430c4b5d562226e4e6ba87881f
