name: kubernetes-client-helper
version: 0.1.0.0
library:
  source-dirs: src
dependencies:
  - base >=4.7 && <5.0
  - kubernetes == 0.1.0.0
  - pem
  - x509
  - tls
  - x509-system
  - x509-store
  - data-default-class
  - connection
  - x509-validation
  - http-client >=0.5 && <0.6
  - http-client-tls
  - microlens >= 0.4.3 && <0.5
  - bytestring >=0.10.0 && <0.11
  - text >=0.11 && <1.3
  - safe-exceptions <0.2



