name: kubernetes-exec-helper
version: 0.1.0.0
library:
  source-dirs: src
dependencies:
  - base >=4.7 && <5.0
  - connection >= 0.2 && < 0.3
  - kubernetes == 0.1.0.0
  - kubeconfig
  - kubernetes-client-helper == 0.1.0.0
  - pem
  - x509
  - tls >= 1.4 && < 1.5
  - x509-system
  - x509-store
  - data-default-class
  - connection
  - x509-validation
  - http-client >=0.5 && <0.6
  - http-client-tls
  - http-types >= 0.9.1 && < 0.10
  - microlens >= 0.4.3 && <0.5
  - bytestring >=0.10.0 && <0.11
  - text >=0.11 && <1.3
  - safe-exceptions <0.2
  - network-uri >= 2.6 &&< 2.7
  - network >= 2.6 && < 2.7
  - websockets >= 0.12 && < 0.13
  - async
  - stm
  - mtl
  - HTTP >= 4000.3.9 && < 4000.3.12
  - optparse-applicative
  - process
  - log-warper >= 1.8.2 && < 1.9
  - tls >= 1.4 && < 1.5
  - wuss 
  - http-client
  - hslogger >= 1.2 && < 1.3
  
executable : 
  main: Exec.hs
  source-dirs: examples
  dependencies: 
    - kubeconfig
    - kubernetes-exec-helper
    - process
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base >=4.7 && <5.0
      - aeson
      - async
      - bytestring >=0.10.0 && <0.11
      - connection
      - data-default-class
      - hlint >= 2.0 && < 3.0
      - hspec
      - HTTP >= 4000.3.9 && < 4000.3.12
      - http-client >=0.5 && <0.6
      - http-client-tls
      - kubeconfig
      - kubernetes == 0.1.0.0
      - kubernetes-client-helper == 0.1.0.0
      - kubernetes-exec-helper == 0.1.0.0
      - log-warper >= 1.8.2 && < 1.9
      - microlens >= 0.4.3 && <0.5
      - mtl
      - network >= 2.6 && < 2.7
      - optparse-applicative
      - pem
      - process
      - safe-exceptions <0.2
      - stm
      - text >=0.11 && <1.3
      - tls
      - websockets >= 0.12 && < 0.13
      - x509
      - x509-store
      - x509-system
      - x509-validation
      - yaml
