name: kubernetes-watch
version: 0.1.0.0
library:
  source-dirs: src
dependencies:
  - base >=4.7 && <5.0
  - aeson >=1.0 && <2.0
  - bytestring >=0.10.0 && <0.11
  - http-client >=0.5 && <0.6
  - mtl >=2.2.1
  - streaming-bytestring >= 0.1.5 && < 0.2.0
  - text >=0.11 && <1.3
  - kubernetes == 0.1.0.0

