on: [push]
name: Cabal
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2.7', '9.4.4']
        cabal: ['3.8.1.0']
        os: [ubuntu-latest]
      fail-fast: false

    name: Cabal GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal build all --enable-tests
      - run: cabal test all
